//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_UusuarioJyM
    {
        public int Id { get; set; }
        public string UsuarioJyM { get; set; }
        public string Acceso { get; set; }
        public bool EstadoUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    }
}
